theme: minima
title: ABOUT ME
author: Andrew Yuen
email: ayuen@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  On occasision, I compete in bike races. I also volunteered in Ecuador one summer and would like to run a marathon one day. 

# social links
instagram_username: a.d.yuen # DO NOT include the @ character, or else the build will fail!
github_username:  ayuen12 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
